services:
  - type: worker
    name: smc-bot
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install ccxt pandas requests numpy
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: SYMBOL
        value: BTC/USDT
      - key: TIMEFRAME
        value: 15m
